<a href="https://colab.research.google.com/github/naseemkp07/Data-analysis/blob/main/Numpy%20module/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1d = np.array([1, 2, 3])

In [ ]:
print(arr1d)

[1 2 3]


In [ ]:
arr2d = np.array([ [1, 2, 3] ,
                   [4, 5, 6] ] )

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6] ,
        [7, 8, 9]
    ]
])

print(arr3d)

NameError: ignored

In [ ]:
arr3dL = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr3dL)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr1d.shape)

(3,)


In [ ]:
print(arr2d.shape)

(2, 3)


In [ ]:
print(arr3d.shape)

(1, 3, 3)


In [ ]:
print(arr3dL.shape)

(2, 2, 3)


In [ ]:
#Check the datatype

arr = np.array([1,2, 3, 4, 5])
type(arr)

numpy.ndarray

In [ ]:
arr1d = np.array([1, 2, 3 , 4, 5 ])
#Access the second element (index 1)
element = arr1d[1]
print(element)

2


In [ ]:
#To slice arrays to extract specific portions of the data

arr1d = np.array([1,4,5,6,7,8,])
slice = arr1d[1:4]
print(slice)

[4 5 6]


In [ ]:
#To reshape arrays using the reshape() method.
arr1d = np.array([1, 2, 3])
print(arr1d)
print("------------------------")
reshaped = arr1d.reshape(3, 1)  # Reshape into a 3x1 matrix
print(reshaped)

[1 2 3]
------------------------
[[1]
 [2]
 [3]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print("-------------------------")
reshaped = arr.reshape(2, 3)
print(reshaped)

[1 2 3 4 5 6]
-------------------------
[[1 2 3]
 [4 5 6]]


In [ ]:
#To iterate over NumPy arrays using loops.
arr1d = np.array([1, 2, 3])
for item in arr1d:
 print(item)

1
2
3


In [ ]:
 #To iterate over NumPy arrays using loops.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for item in arr:
            print(item)


1
2
3
4
5


In [ ]:
#Returns the shape (dimensions) of the array.

arr = np.array([1, 2, 3, 4, 5, 6])
shape = arr.shape
print(shape)

(6,)


In [ ]:
arr2d = np.array([
                  [1, 2, 3, 4],
                  [4, 5, 6, 7]

                 ]
                 )
shape = arr2d.shape
print(shape)

(2, 4)


In [ ]:
#3 dimensional
arr3d = np.array([ [
                  [1, 2, 3, 4],
                  [4, 5, 6, 7] ,
                  [8 , 7, 6,  5]
                   ]
                 ]
                 )
shape = arr3d.shape
print(shape)

(1, 3, 4)


In [ ]:
# 3 dimensional array
arr3d = np.array([[
                  [1, 2, 3],
                   [4, 5, 6]
                  ]
                 ,
                  [
                      [1, 2, 3],
                      [4, 5, 6]
                  ]
                 ]
                )
shape = arr3d.shape
print(shape)


(2, 2, 3)


In [ ]:
sample_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Dimensions of 'sample_2d_array' = ", sample_2d_array.ndim)

Dimensions of 'sample_2d_array' =  2


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Dimensions of 'array_of_integers' = ", arr.ndim)


Dimensions of 'array_of_integers' =  1


In [ ]:
#Returns the total number of elements in the array.

array_of_integers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"The total number of elements in our array 'array_of_integers' = {array_of_integers.size}")
print({array_of_integers.size})

The total number of elements in our array 'array_of_integers' = 10
{10}


In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array.dtype)


int64


In [ ]:
my_array = np.array([1, 2.0, 3, 4, 5, 'abc'])
print(my_array.dtype)


<U32


In [ ]:
#Changes the data type of the array.

arr1 = np.array([2, 3, 4])
print(arr1)
print(arr1.dtype)
print("-----------------------")
arr2 = arr1.astype('float64')
print(arr2)
print(arr2.dtype)

[2 3 4]
int64
-----------------------
[2. 3. 4.]
float64


In [ ]:
import numpy as np
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate the arrays along the 0th axis (resulting in a longer 1D array)
result = np.concatenate((arr1, arr2), axis=0)
print(result)

[1 2 3 4 5 6]


In [ ]:

import numpy as np
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6 ])
# Split the array into two subarrays along the 0th axis
subarrays = np.split(arr, 3, axis=0)
print(subarrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
indices = np.where(arr > 3)  # Find indices where elements are greater than 3
print(indices)


(array([3, 4, 5]),)


In [ ]:
import numpy as np
arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)


[1 2 3 4 5]


In [ ]:
#Filtering Arrays using Boolean Indexing:
#You can create new arrays with elements that meet specific conditions using Boolean indexing

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
condition = arr > 3
filtered_arr = arr[condition]  # Create a new array with elements greater than 3
print(filtered_arr)

[4 5 6]


In [ ]:
import numpy as np
arr = np.array([41, 40, 42, 43, 44])
x = [True, True, False, True, False]
newarr = arr[x]
print(newarr)


[41 40 43]


In [ ]:
table = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

table


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**slicing rows**

In [ ]:
# Extract the second row (index 1)
row = table[1, :]
row

array([4, 5, 6])

In [ ]:
# Extract rows 0 and 1
rows = table[0:2 , :]
rows

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Extract all rows starting from the second row
remaining_rows = table[1: , :]
remaining_rows

array([[4, 5, 6],
       [7, 8, 9]])

**Slicing columns**

In [ ]:
# Extract the second column (index 1)
column = table[:, 1]
column

array([2, 5, 8])

In [ ]:
# Extract columns 0 and 2
columns = table[: , [0, 2]]
columns

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
table = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

table

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Slicing Specific Rows and Columns:
subset = table[1:3, [0, 2]]
subset

array([[4, 6],
       [7, 9]])

In [ ]:
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Extract the first "layer"
layer1 = arr3d[0, :, :]
layer1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Extract the second "layer"
layer2 = arr3d[1, :, :]
layer2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Extract the first row from both layers
first_row = arr3d[:, 0, :]
first_row

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# Extract the second row from the second layer
second_row_layer2 = arr3d[1, 1, :]
second_row_layer2

array([10, 11, 12])

In [ ]:
# Extract the first column from both layers
first_column = arr3d[:, :, 0]
first_column

array([[ 1,  4],
       [ 7, 10]])

In [ ]:
# Extract the third column from the first layer
third_column_layer1 = arr3d[0, 1, 2]
third_column_layer1

6

In [ ]:
# An uninitialized array is created using np.empty(shape, dtype), and its values are not initialized.
# The values in the array can be arbitrary and are not guaranteed to be zeros or any specific value.

import numpy as np
uninitialized_array = np.empty([5, 3])
print(uninitialized_array)


[[4.96957567e-310 0.00000000e+000 1.97250832e-153]
 [1.10159478e+253 4.99955025e+228 1.96873339e-153]
 [4.40571859e-085 9.17652394e+199 1.10155749e+253]
 [5.76353811e+228 1.96873339e-153 4.40571859e-085]
 [9.17652394e+199 8.76163865e+245 1.34584862e-284]]


In [ ]:
# Initialized with Zeros:
# You can create an array initialized with zeros using np.zeros(shape, dtype).

import numpy as np
zeros_array = np.zeros((3, 3))  # Default dtype is float

print(zeros_array)
print("-----------------------")
another_zeros_array = np.zeros((3, 3), dtype=int)
print(another_zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# Initialized with Ones:
# You can create an array initialized with ones using np.ones(shape, dtype).


import numpy as np
ones_array = np.ones((3, 3))  # Default dtype is float
print(ones_array)
print("---------------------------")
another_ones_array = np.ones((3, 3), dtype=int)
print(another_ones_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------------------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Array from Numerical Ranges:
# You can create an array with values generated from a numerical range using np.arange(start, stop, step, dtype)


import numpy as np
array_with_range = np.arange(5)
print(array_with_range)

print("------------------------------")
another_array_with_range = np.arange(10, 20, 2)
print(another_array_with_range)

[0 1 2 3 4]
------------------------------
[10 12 14 16 18]


In [ ]:
# Array from Random Numbers:
# You can create an array with random numbers using np.random.random(shape) or np.random.randint(low, high, size).


import numpy as np
random_array = np.random.random((4, 3))
print(random_array)
print("-------------------------------")
random_integral_array = np.random.randint(0, 5, size=(2, 3, 4))
print(random_integral_array)
print("--------------------")
a=np.random.randint(1000)
print(a)

[[0.51263547 0.23835448 0.03400026]
 [0.39700723 0.38769248 0.09677076]
 [0.54556538 0.10000016 0.55403378]
 [0.28021242 0.26832999 0.23409468]]
-------------------------------
[[[1 4 3 4]
  [0 1 4 2]
  [0 4 1 3]]

 [[0 0 1 3]
  [4 3 1 0]
  [4 4 4 4]]]
--------------------
143


In [ ]:
# Mean (Average):
# Calculate the arithmetic mean of the array values.
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 3.0


In [ ]:
# Find the middle value of the sorted array. If the array has an even number of elements,
# the median is the average of the two middle values.
import numpy as np
data = np.array([1, 2, 3, 4, 5])
median_value = np.median(data)
print("Median:", median_value)


Median: 3.0


In [ ]:
# Calculate the standard deviation, which measures the spread or dispersion of data.
import numpy as np
data = np.array([1, 2, 3, 4, 5])
std_deviation = np.std(data)
print("Standard Deviation:", std_deviation)

Standard Deviation: 1.4142135623730951


In [ ]:
# .Variance:
# Find the variance, which is the average of the squared differences from the Mean.
import numpy as np
data = np.array([1, 2, 3, 4, 5])
variance = np.var(data)
print("Variance:", variance)

Variance: 2.0


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
min_value = np.min(data)
max_value = np.max(data)
print("Minimum:", min_value)
print("Maximum:", max_value)

Minimum: 1
Maximum: 5


In [ ]:
# Calculate the sum and product of all the elements in the array.
import numpy as np
data = np.array([1, 2, 3, 4,5,6,7])
sum_value = np.sum(data)
product_value = np.prod(data)
print("Sum:", sum_value)
print("Product:", product_value)

Sum: 28
Product: 5040
